# -*- coding: utf-8 -*-
"""
ai_commander.py — Real-Time DeepSeek AI Swarm Tactical Commander

Provides asynchronous, non-blocking tactical evaluation and multi-agent coordination
powered by the DeepSeek LLM (deepseek-v4-flash / deepseek-v4-pro).

Key Capabilities:
- Asynchronous Non-Blocking Loop: Never stalls the 100 Hz MuJoCo simulation or 60 Hz telemetry.
- Chain-of-Thought Military Reasoning: Captures raw reasoning tokens for real-time HUD streaming.
- Structured Tactical Directives: Dynamic strategic postures, priority targets, and enclosure angles.
- Human-in-the-Loop Operator Uplink: Direct natural language orders from the visualizer console.
"""

from __future__ import annotations
import os
import time
import json
import urllib.request
import urllib.error
import threading
from dataclasses import dataclass, field
from typing import Dict, List, Optional, Any
from pathlib import Path


def _load_env():
    """Load credentials from local .env if present."""
    env_file = Path(__file__).resolve().parent.parent / ".env"
    if env_file.exists():
        for line in env_file.read_text(encoding="utf-8").splitlines():
            line = line.strip()
            if line and not line.startswith("#") and "=" in line:
                k, v = line.split("=", 1)
                os.environ.setdefault(k.strip(), v.strip())


_load_env()

DEFAULT_API_KEY = os.environ.get("DEEPSEEK_API_KEY", "")
DEFAULT_BASE_URL = os.environ.get("DEEPSEEK_BASE_URL", "https://api.deepseek.com")
DEFAULT_MODEL = os.environ.get("DEEPSEEK_COMMANDER_MODEL", "deepseek-v4-flash")


@dataclass
class TacticalDirective:
    """A formal tactical directive generated by the DeepSeek AI Swarm Commander."""
    timestamp: float
    sim_time: float
    strategic_posture: str
    target_priority: List[int]
    drone_assignments: Dict[int, Dict[str, Any]]
    tactical_radio_broadcast: str
    reasoning_chain: str
    model: str
    latency_s: float
    token_usage: Dict[str, int]
    operator_override: bool = False

    def to_dict(self) -> Dict[str, Any]:
        return {
            "timestamp": round(self.timestamp, 3),
            "sim_time": round(self.sim_time, 2),
            "strategic_posture": self.strategic_posture,
            "target_priority": self.target_priority,
            "drone_assignments": self.drone_assignments,
            "tactical_radio_broadcast": self.tactical_radio_broadcast,
            "reasoning_chain": self.reasoning_chain,
            "model": self.model,
            "latency_s": round(self.latency_s, 2),
            "token_usage": self.token_usage,
            "operator_override": self.operator_override,
        }


SYSTEM_PROMPT = """You are the Autonomous Multi-Agent Drone Swarm Tactical Commander for Operation MRD-Swarm.
You command 4 heterogeneous quadrotors in a dense 3D urban environment:
- Drone 0 (Heavy Scout): Long-range optics, wide search envelope.
- Drone 1 (Fast Interceptor): 18 m/s sprint speed, pincer cutoffs.
- Drone 2 (Thermal Surveyor): FLIR sensor, penetrates target smoke.
- Drone 3 (Comms Relay): High-altitude mesh anchor (Z=10.5m), overcomes EW jamming.

TACTICAL RULES:
1. If smoke is active on a target, assign Thermal Surveyor (D2) to TRACKER.
2. If EW jamming active, ensure Comms Relay (D3) maintains altitude centroid.
3. Fast Interceptor (D1) flanks high-priority moving HVTs to cut off escape corridors.

Be concise in your military reasoning. Always output valid JSON only:
{
  "strategic_posture": "CONCENTRIC_CONTAINMENT" | "AGGRESSIVE_PINCER" | "COORDINATED_SWEEP" | "THERMAL_IR_PURSUIT" | "RF_RELAY_PRESERVATION",
  "target_priority": [target_id, ...],
  "drone_assignments": {
    "0": {"role": "EXPLORER" | "TRACKER" | "FLANKER", "target_id": 0, "desired_speed": 10.0, "tactic": "..."},
    "1": {"role": "FLANKER" | "TRACKER", "target_id": 0, "desired_speed": 16.0, "tactic": "..."},
    "2": {"role": "TRACKER" | "EXPLORER", "target_id": 0, "desired_speed": 12.0, "tactic": "..."},
    "3": {"role": "RELAY", "target_id": null, "desired_speed": 5.5, "tactic": "Maintain altitude anchor"}
  },
  "tactical_radio_broadcast": "Military radio transmission string (e.g. 'Falcon-Lead to Swarm: Target HVT-0 confirmed... Over.')"
}"""


class DeepSeekSwarmCommander:
    """
    Asynchronous Tactical Commander that periodically queries DeepSeek LLM
    without blocking real-time physics or telemetry loops.
    """

    def __init__(
        self,
        api_key: Optional[str] = None,
        base_url: Optional[str] = None,
        model: Optional[str] = None,
        update_interval_s: float = 3.5,
    ):
        self.api_key = api_key or os.environ.get("DEEPSEEK_API_KEY", DEFAULT_API_KEY)
        self.base_url = (base_url or os.environ.get("DEEPSEEK_BASE_URL", DEFAULT_BASE_URL)).rstrip("/")
        self.model = model or os.environ.get("DEEPSEEK_COMMANDER_MODEL", DEFAULT_MODEL)
        self.update_interval_s = update_interval_s

        self.latest_directive: Optional[TacticalDirective] = None
        self.directive_history: List[TacticalDirective] = []

        self._lock = threading.Lock()
        self._is_in_flight = False
        self._last_request_time = 0.0
        self._pending_operator_cmd: Optional[str] = None

        # Fallback default initial directive
        self._set_default_directive()

    def _set_default_directive(self):
        """Initial baseline directive before first LLM completion."""
        self.latest_directive = TacticalDirective(
            timestamp=time.time(),
            sim_time=0.0,
            strategic_posture="COORDINATED_SWEEP",
            target_priority=[0, 1, 2],
            drone_assignments={
                0: {"role": "EXPLORER", "target_id": None, "desired_speed": 8.5, "tactic": "Frontier exploration"},
                1: {"role": "FLANKER", "target_id": 0, "desired_speed": 15.5, "tactic": "High-speed interception"},
                2: {"role": "TRACKER", "target_id": 0, "desired_speed": 12.0, "tactic": "Thermal acquisition"},
                3: {"role": "RELAY", "target_id": None, "desired_speed": 5.5, "tactic": "Centroid altitude anchor"},
            },
            tactical_radio_broadcast="Command-Net initialized. Swarm airborne. Establishing RF mesh and initiating urban frontier sweep. Over.",
            reasoning_chain="System startup: Initializing baseline tactical posture. Establishing RF mesh connectivity while all drones ascend to operational altitudes.",
            model=self.model,
            latency_s=0.0,
            token_usage={"total_tokens": 0},
            operator_override=False,
        )

    def submit_operator_command(self, command_text: str):
        """Submit a natural language directive from the human operator (Human-in-the-Loop)."""
        with self._lock:
            self._pending_operator_cmd = command_text
            print(f"[AI COMMANDER] Operator order received: '{command_text}'")

    def get_latest_directive(self) -> TacticalDirective:
        """Thread-safe retrieval of the active directive."""
        with self._lock:
            return self.latest_directive

    def request_tactical_update(
        self,
        sim_time: float,
        drone_states: Dict[int, Any],
        target_tracks: Dict[int, Any],
        detected_target_ids: List[int],
        uncertainty_pct: float,
        ew_jamming_active: bool,
        active_smokes: List[int],
        mission_phase: str,
        force: bool = False,
    ):
        """
        Asynchronously triggers an LLM tactical evaluation if interval has elapsed
        or if forced (e.g. operator command or target lost).
        Non-blocking: immediately returns.
        """
        now = time.time()
        with self._lock:
            if self._is_in_flight:
                return  # Request already executing in background thread
            if not force and (now - self._last_request_time) < self.update_interval_s and not self._pending_operator_cmd:
                return
            self._is_in_flight = True
            self._last_request_time = now

            # Consume any pending operator command
            operator_cmd = self._pending_operator_cmd
            self._pending_operator_cmd = None

        # Build prompt payload
        telemetry_payload = {
            "sim_time_s": round(sim_time, 2),
            "mission_phase": mission_phase,
            "uncertainty_pct": round(uncertainty_pct, 1),
            "ew_jamming_active": ew_jamming_active,
            "active_smokes_target_ids": active_smokes,
            "detected_targets_now": detected_target_ids,
            "drones": {
                did: {
                    "pos": [round(p, 1) for p in d.get("pos", [0, 0, 0])],
                    "speed_mps": round(d.get("speed", 0.0), 1),
                    "battery_pct": round(d.get("battery", 100.0), 1),
                    "role": d.get("role", "EXPLORER"),
                }
                for did, d in drone_states.items()
            },
            "targets": {
                tid: {
                    "state": tr.get("state", "UNKNOWN"),
                    "pos": [round(p, 1) for p in tr["pos"]] if tr.get("pos") else None,
                    "age_s": round(tr.get("age_s", 0.0), 1),
                    "uncertainty_m": round(tr.get("uncertainty_m", 0.0), 1),
                }
                for tid, tr in target_tracks.items()
            }
        }

        # Launch background worker
        thread = threading.Thread(
            target=self._execute_llm_query,
            args=(sim_time, telemetry_payload, operator_cmd),
            daemon=True,
            name="DeepSeekSwarmCommanderWorker"
        )
        thread.start()

    def _execute_llm_query(self, sim_time: float, telemetry: Dict[str, Any], operator_cmd: Optional[str]):
        """Runs in background thread to call DeepSeek API."""
        t0 = time.time()
        try:
            user_content = f"CURRENT BATTLEFIELD TELEMETRY:\n{json.dumps(telemetry, indent=2)}\n"
            if operator_cmd:
                user_content += f"\n*** DIRECT HUMAN OPERATOR DIRECTIVE: ***\n\"{operator_cmd}\"\nPrioritize and integrate this directive immediately into the swarm's tactical orders.\n"

            req_data = json.dumps({
                "model": self.model,
                "messages": [
                    {"role": "system", "content": SYSTEM_PROMPT},
                    {"role": "user", "content": user_content}
                ],
                "max_tokens": 4096,
                "temperature": 0.25,
            }).encode("utf-8")

            url = f"{self.base_url}/chat/completions"
            req = urllib.request.Request(
                url,
                data=req_data,
                headers={
                    "Authorization": f"Bearer {self.api_key}",
                    "Content-Type": "application/json",
                }
            )

            with urllib.request.urlopen(req, timeout=35.0) as resp:
                result = json.loads(resp.read().decode("utf-8"))

            latency = time.time() - t0
            choice = result["choices"][0]
            msg = choice["message"]
            raw_content = msg.get("content", "").strip()
            reasoning = msg.get("reasoning_content", "").strip()
            usage = result.get("usage", {})

            # Robust JSON extraction
            parsed = None
            for candidate in [raw_content, reasoning]:
                if not candidate:
                    continue
                # Try finding JSON block between { and }
                s_idx = candidate.find("{")
                e_idx = candidate.rfind("}")
                if s_idx != -1 and e_idx != -1 and e_idx > s_idx:
                    try:
                        parsed = json.loads(candidate[s_idx:e_idx+1])
                        break
                    except Exception:
                        pass

            if not parsed:
                parsed = {
                    "strategic_posture": "COORDINATED_SWEEP",
                    "target_priority": [0, 1, 2],
                    "drone_assignments": {},
                    "tactical_radio_broadcast": "Command acknowledged. Maintain tactical perimeter.",
                }

            directive = TacticalDirective(
                timestamp=time.time(),
                sim_time=sim_time,
                strategic_posture=parsed.get("strategic_posture", "COORDINATED_SWEEP"),
                target_priority=parsed.get("target_priority", [0, 1, 2]),
                drone_assignments=parsed.get("drone_assignments", {}),
                tactical_radio_broadcast=parsed.get("tactical_radio_broadcast", "Broadcast acknowledged."),
                reasoning_chain=reasoning if reasoning else "Tactical evaluation executed based on current target velocity and mesh state.",
                model=self.model,
                latency_s=latency,
                token_usage=usage,
                operator_override=bool(operator_cmd),
            )

            with self._lock:
                self.latest_directive = directive
                self.directive_history.append(directive)
                if len(self.directive_history) > 50:
                    self.directive_history.pop(0)

            print(f"[AI COMMANDER] LLM Tactical Order (latency {latency:.2f}s): {directive.strategic_posture} | Radio: '{directive.tactical_radio_broadcast[:60]}...'")

        except Exception as e:
            latency = time.time() - t0
            print(f"[AI COMMANDER ERROR] DeepSeek query failed ({latency:.2f}s): {e}")
        finally:
            with self._lock:
                self._is_in_flight = False
